apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "session-manager-server.fullname" . }}
  labels:
    {{- include "session-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    admin:
      port: {{ .Values.adminPort }}
    server:
      port: {{ .Values.httpPort }}
      agentPort: {{ .Values.agentHttpPort }}
      # Be able to inject TLS if set
      {{- if .Values.tls.enable -}}
      tls:
        cert: /var/run/tls/tls.crt
        key: /var/run/tls/tls.key
      {{- end }}
      auth:
        jwks:
          url: {{ .Values.auth.jwks.Url }}
          refreshInterval: {{ .Values.auth.jwks.certRefreshInterval }}
      identifier:
        static:
          id: {{ .Values.identifier.static.id }}
      allowedOriginHosts:
      {{- toYaml .Values.allowedOriginHosts | nindent 6 }}